travis:
  secure:
    BINSTAR_TOKEN: inXo9+xuw+/i7ARMBH/XIw2Z+1PFnMa3163FFZaOrSbNp3ChDo4iVd/JjwXjYCAKGwWYspeTwtDp1GfQY/jXp/2Bpze1TDVN+Zi0yzGB/Gy/IqtChwTNtN7tBoDC215vKISbe9QG80KQ0W5sIjznTex2FvUQsXJS8rv4es97Cl6iUnaeYoJckfhCAVlApytTCy9fsI2/zUNhLulEKDROJ+/zph2tO2rYjS7SFMilpfo0ijn2mUoh+2Vyb+eCptTl8JVmq8cpH9Y6NQkHmk7FRlPcfUl+W4nqUYWM3eL/tTVE3Xj1DfGLdAyNiHMa0116JnNYJyo5/pchG+iz8DAg1VFW4XC0jgqcvopdvqMcccLtxNt3TWTFEYvt3Y9ZwcvT+/qaUwlBwAndpSytAtGo0owtonpzwxL90IoU3VgrGYGs4mWwiKeseP/fM1/+cI1xaGsIKUTKAvHtA9ZsZnhRNs1Qbg8DJL9lAR6nKHZxJEnlyxarER0FcmrAmoiamTdY/P1WmJ1zRzP7yKb4M0BGyHln7mGOei9b5rDEwtrF29KsS586FZiBDEa/OUadfSLvJ2ZlBgAC4Zov8j158rouUDN8398jVxxCEr5o1L3rw3ii4Bao0xqUEtIh9RlYlzN567s501zcpl/fb+0XEG+MXAPv8PEbC9jLTABDpvIS2ag=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
